wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1744656043.703046
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.11.0
      5: 0.15.11
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
pruningType:
  desc: null
  value: class-blind
percentage:
  desc: null
  value: 0.1
